INSERT INTO books(key,title) VALUES ('OT','Genesis');
INSERT INTO books(key,title) VALUES ('OT','Exodus');
INSERT INTO books(key,title) VALUES ('OT','Leviticus');
INSERT INTO books(key,title) VALUES ('OT','Numbers');
INSERT INTO books(key,title) VALUES ('OT','Deuteronomy');
INSERT INTO books(key,title) VALUES ('OT','Joshua');
INSERT INTO books(key,title) VALUES ('OT','Judges');
INSERT INTO books(key,title) VALUES ('OT','Ruth');
INSERT INTO books(key,title) VALUES ('OT','1 Samuel');
INSERT INTO books(key,title) VALUES ('OT','2 Samuel');
INSERT INTO books(key,title) VALUES ('OT','1 Kings');
INSERT INTO books(key,title) VALUES ('OT','2 Kings');
INSERT INTO books(key,title) VALUES ('OT','1 Chronicles');
INSERT INTO books(key,title) VALUES ('OT','2 Chronicles');
INSERT INTO books(key,title) VALUES ('OT','Ezra');
INSERT INTO books(key,title) VALUES ('OT','Nehemiah');
INSERT INTO books(key,title) VALUES ('OT','Esther');
INSERT INTO books(key,title) VALUES ('OT','Job');
INSERT INTO books(key,title) VALUES ('OT','Psalms');
INSERT INTO books(key,title) VALUES ('OT','Proverbs');
INSERT INTO books(key,title) VALUES ('OT','Ecclesiastes');
INSERT INTO books(key,title) VALUES ('OT','Solomon''s Song');
INSERT INTO books(key,title) VALUES ('OT','Isaiah');
INSERT INTO books(key,title) VALUES ('OT','Jeremiah');
INSERT INTO books(key,title) VALUES ('OT','Lamentations');
INSERT INTO books(key,title) VALUES ('OT','Ezekiel');
INSERT INTO books(key,title) VALUES ('OT','Daniel');
INSERT INTO books(key,title) VALUES ('OT','Hosea');
INSERT INTO books(key,title) VALUES ('OT','Joel');
INSERT INTO books(key,title) VALUES ('OT','Amos');
INSERT INTO books(key,title) VALUES ('OT','Obadiah');
INSERT INTO books(key,title) VALUES ('OT','Jonah');
INSERT INTO books(key,title) VALUES ('OT','Micah');
INSERT INTO books(key,title) VALUES ('OT','Nahum');
INSERT INTO books(key,title) VALUES ('OT','Habakkuk');
INSERT INTO books(key,title) VALUES ('OT','Zephaniah');
INSERT INTO books(key,title) VALUES ('OT','Haggai');
INSERT INTO books(key,title) VALUES ('OT','Zechariah');
INSERT INTO books(key,title) VALUES ('OT','Malachi');
INSERT INTO books(key,title) VALUES ('NT','Matthew');
INSERT INTO books(key,title) VALUES ('NT','Mark');
INSERT INTO books(key,title) VALUES ('NT','Luke');
INSERT INTO books(key,title) VALUES ('NT','John');
INSERT INTO books(key,title) VALUES ('NT','Acts');
INSERT INTO books(key,title) VALUES ('NT','Romans');
INSERT INTO books(key,title) VALUES ('NT','1 Corinthians');
INSERT INTO books(key,title) VALUES ('NT','2 Corinthians');
INSERT INTO books(key,title) VALUES ('NT','Galatians');
INSERT INTO books(key,title) VALUES ('NT','Ephesians');
INSERT INTO books(key,title) VALUES ('NT','Philippians');
INSERT INTO books(key,title) VALUES ('NT','Colossians');
INSERT INTO books(key,title) VALUES ('NT','1 Thessalonians');
INSERT INTO books(key,title) VALUES ('NT','2 Thessalonians');
INSERT INTO books(key,title) VALUES ('NT','1 Timothy');
INSERT INTO books(key,title) VALUES ('NT','2 Timothy');
INSERT INTO books(key,title) VALUES ('NT','Titus');
INSERT INTO books(key,title) VALUES ('NT','Philemon');
INSERT INTO books(key,title) VALUES ('NT','Hebrews');
INSERT INTO books(key,title) VALUES ('NT','James');
INSERT INTO books(key,title) VALUES ('NT','1 Peter');
INSERT INTO books(key,title) VALUES ('NT','2 Peter');
INSERT INTO books(key,title) VALUES ('NT','1 John');
INSERT INTO books(key,title) VALUES ('NT','2 John');
INSERT INTO books(key,title) VALUES ('NT','3 John');
INSERT INTO books(key,title) VALUES ('NT','Jude');
INSERT INTO books(key,title) VALUES ('NT','Revelation');
INSERT INTO books(key,title) VALUES ('BOM','1 Nephi');
INSERT INTO books(key,title) VALUES ('BOM','2 Nephi');
INSERT INTO books(key,title) VALUES ('BOM','Jacob');
INSERT INTO books(key,title) VALUES ('BOM','Enos');
INSERT INTO books(key,title) VALUES ('BOM','Jarom');
INSERT INTO books(key,title) VALUES ('BOM','Omni');
INSERT INTO books(key,title) VALUES ('BOM','Words of Mormon');
INSERT INTO books(key,title) VALUES ('BOM','Mosiah');
INSERT INTO books(key,title) VALUES ('BOM','Alma');
INSERT INTO books(key,title) VALUES ('BOM','Helaman');
INSERT INTO books(key,title) VALUES ('BOM','3 Nephi');
INSERT INTO books(key,title) VALUES ('BOM','4 Nephi');
INSERT INTO books(key,title) VALUES ('BOM','Mormon');
INSERT INTO books(key,title) VALUES ('BOM','Ether');
INSERT INTO books(key,title) VALUES ('BOM','Moroni');
INSERT INTO books(key,title) VALUES ('DC','Sections 1-19');
INSERT INTO books(key,title) VALUES ('DC','Sections 20-39');
INSERT INTO books(key,title) VALUES ('DC','Sections 40-59');
INSERT INTO books(key,title) VALUES ('DC','Sections 60-79');
INSERT INTO books(key,title) VALUES ('DC','Sections 80-99');
INSERT INTO books(key,title) VALUES ('DC','Sections 100-119');
INSERT INTO books(key,title) VALUES ('DC','Sections 120-138');
INSERT INTO books(key,title) VALUES ('PGP','Moses');
INSERT INTO books(key,title) VALUES ('PGP','Abraham');
